### ISSUE TITLE
Sprint 2: Define Full Set of User Stories

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#1]

**Comment by Forsm0** [comment]
Rough designs of the screens (pages) that your application will have and how these flow together. We are looking for wireframes and a high-level overview of how the application flows together. For example, see the following resources:
[How to create a user experience flow chart (UX Flow Chart) (startuprocket.com)](https://www.startuprocket.com/articles/how-to-create-a-user-experience-flow-chart-ux-flow-chart)
[Mobile Application Design : Paper Prototype Video - YouTube](https://www.youtube.com/watch?v=y20E3qBmHpg)

**Comment by ShajiRahman** [comment]
I take responsibility for this.

**Comment by Forsm0** [comment]
Suggestions:
Add the payment feature and automated email use cases.
Consider linking pre-order meals to the menu for better clarity.
Label your actors more specifically (e.g., "Customer," "Restaurant Admin").
Merge Register and Account Creation if they represent the same process.

**Comment by Forsm0** [comment]
you could consider adding user stories for payment integration and automated emails, which were part of the original proposal. These additions would ensure all features are covered in the user stories, even if they're optional.

**Comment by Forsm0** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)

**Comment by Forsm0** [comment]
How is the list of user stories coming along?
