### ISSUE TITLE
Sprint 2: Create Sequence Diagrams

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#10]
A sequence diagram is a Unified Modeling Language (UML) diagram that illustrates the sequence of messages between objects in an interaction. A sequence diagram consists of a group of objects that are represented by lifelines, and the messages that they exchange over time during the interaction.

**Comment by Forsm0** [comment]
Suggested Sequence Diagrams:

- [ ] Making a Reservation:
> This diagram shows the interaction between the customer, the reservation system, and table availability. It covers the process from checking available tables to booking a reservation.

- [ ] Pre-ordering Meals:
> This diagram focuses on the interaction where the customer selects a restaurant, views the menu, and pre-orders meals for their reservation.

- [ ] Cancelling a Reservation:
> This diagram shows the flow of interactions when a customer cancels an existing reservation, including how the system updates the reservation and table availability.

- [ ] Viewing Available Restaurants and Menus:
> This diagram outlines the interaction where the customer browses restaurants, views their profiles (contact information, table availability), and checks the menu items for pre-ordering.

**Comment by Forsm0** [comment]
![Image](https://github.com/user-attachments/assets/c12b9bc3-a5ff-4d1c-a8bf-ad1fe0fb9d05)


Any feedback or comments

**Comment by Forsm0** [comment]
Should we have one for restaurant owner to pull the reservations from database?

**Comment by Forsm0** [comment]
![Image](https://github.com/user-attachments/assets/d168bafe-740d-4d80-b772-99fbfc661c61)

This is the revised sequence diagram for "making a reservation". Can someone have a look and tell me if it looks okay?

**Comment by Forsm0** [comment]
![Image](https://github.com/user-attachments/assets/f776b903-59f3-4f4c-9af2-c1ccf6ea3ad0)

This is for restaurant owner to view reservations. Any feedback?

**Comment by Forsm0** [comment]
![Image](https://github.com/user-attachments/assets/42a0984e-7911-412a-95c5-917a2eb3fa01)

And when a customer wants to view the menu, but not book. Any feedback?

**Comment by ammadkhan34** [comment]
> ![Image](https://private-user-images.githubusercontent.com/162355418/380208117-d168bafe-740d-4d80-b772-99fbfc661c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Nzg4ODQsIm5iZiI6MTcyOTg3ODU4NCwicGF0aCI6Ii8xNjIzNTU0MTgvMzgwMjA4MTE3LWQxNjhiYWZlLTc0MGQtNGQ4MC1iNzcyLTk5ZmJmYzY2MWM2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNzQ5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODM2ZTk0MGFhYTdkMWEwMTI1ODViYjAwY2I2YTJlMTYwMjgzZDkwNzA4Y2I0YTdkZWRhYTVjNjYxOWFjMWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1bkQNKBWW7d2zFH_ZpbsOgjxv76Mv7KTuJFXuKzaCyw)
> 
> This is the revised sequence diagram for "making a reservation". Can someone have a look and tell me if it looks okay?

given some feedback for first diagram but optional

**Comment by ammadkhan34** [comment]
@Forsm0  Are we adding any updates for review given by momina
