### ISSUE TITLE
Sprint 2: Review Personas

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#11]
The goal of this task is to review the user personas created in Sprint 1 to ensure they accurately represent the target users of the DineSmart system. These personas should guide the design and development of the system’s features, ensuring that the application meets user needs effectively.

Steps:
Review each persona:
Revisit the personas created for the system (e.g., customer, restaurant owner).
Ensure each persona has sufficient detail about their goals, needs, and frustrations.
Verify that the personas align with the current system functionality and reflect any changes or additions made since Sprint 1.

Update personas if needed:
Make any necessary updates to the personas if new insights or requirements have emerged.

Confirm alignment with user stories:
Ensure that the user stories defined in Sprint 2 are aligned with the personas’ goals.
Cross-check that the user stories accurately reflect the personas’ needs.

Outcome:
The personas should be updated and confirmed as relevant and useful for guiding the rest of the project, ensuring that all key user needs are addressed in the design and development phases.

**Comment by ShajiRahman** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)

**Comment by Forsm0** [comment]
I've reviewed and updated the personas
You can find it under the persona section in the report [here](https://roehamptonprod-my.sharepoint.com/:w:/r/personal/forsmok_roehampton_ac_uk/Documents/Documents/Software%20Development%202/Project/Sprint%202/[Sprint2-document.docx](https://roehamptonprod-my.sharepoint.com/:w:/r/personal/forsmok_roehampton_ac_uk/Documents/Documents/Software%20Development%202/Project/Sprint%202/Sprint2-document.docx?d=w7ac634f604ba468b84adb384fc022478&csf=1&web=1&e=McwoZZ)?d=w7ac634f604ba468b84adb384fc022478&csf=1&web=1&e=McwoZZ)

**Comment by ammadkhan34** [comment]
i've reviews and its okay

**Comment by ammadkhan34** [comment]
its done and given chance to every one to review
