### ISSUE TITLE
Sprint 2: Create UX Flow Chart (High-level overview)

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#12]
The goal of this task is to create a high-level UX (User Experience) flow chart that maps out the user journey within the DineSmart system. This flow chart should visually represent the steps users take when interacting with the application, from logging in to making reservations and pre-ordering meals.

Steps:
Identify key user actions:
List the key actions users (both customers and restaurant owners) will take in the system.
These actions should include browsing restaurants, checking table availability, making reservations, and pre-ordering meals.

Map the user journey:
Create a flow chart that shows how users move through the system, starting from login and proceeding to the various features (restaurant selection, reservation, pre-order, etc.).
Ensure that all user interactions with the system are clearly mapped and that the flow is intuitive and user-friendly.

Use appropriate tools:
Use tools like Figma, Draw.io, or any preferred design tool to create the flow chart.
Ensure the flow chart is clear, easy to follow, and reflects the user stories and personas.

Review the flow:
Check that the UX flow chart aligns with the user stories defined in Sprint 2 and the personas created.
Ensure that the flow addresses the key needs and goals of the target users.

Outcome:
A high-level UX flow chart that provides a clear overview of how users will navigate the DineSmart system. This flow chart will guide the UI design and development of the application’s features.

**Comment by ShajiRahman** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)
