### ISSUE TITLE
Sprint 2: Finalising the PDF

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#13]
Finalise the PFD and make it ready for submission.

Link to document [here](https://roehamptonprod-my.sharepoint.com/:w:/r/personal/forsmok_roehampton_ac_uk/Documents/Documents/Software%20Development%202/Project/Sprint%202/[Sprint2-document.docx](https://roehamptonprod-my.sharepoint.com/:w:/r/personal/forsmok_roehampton_ac_uk/Documents/Documents/Software%20Development%202/Project/Sprint%202/Sprint2-document.docx?d=w7ac634f604ba468b84adb384fc022478&csf=1&web=1&e=McwoZZ)?d=w7ac634f604ba468b84adb384fc022478&csf=1&web=1&e=McwoZZ).

**Comment by Forsm0** [comment]
Can someone have a look at the report and give some feedback. Not everything is ready but the majority is.

**Comment by eniola07** [comment]
the hyperlink to the document doesn't work ,returns a 404 not found

**Comment by Forsm0** [comment]
@eniola07 sorry, the link is in teams.
