### ISSUE TITLE
Sprint 3: Database Schema Definition and Modeling

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#15]
Priority: High
Description: Complete the foundational database setup, which is critical for backend and front-end data integration in later weeks.

**Establish a well-defined database schema with both logical (ERD) and physical (table creation) models.**

- [ ] Create Entity-Relationship Diagram (ERD): Identify key entities (tables) and their relationships, targeting up to 5 tables. 

- [ ] Develop Logical Model: Map out tables with fields and data types in an ERD, including primary keys and foreign keys.

- [ ] Design Physical Data Model: Use phpMyAdmin to translate the ERD into a physical database model by creating tables with appropriate columns, data types, primary keys, and foreign keys.

- [ ] Document Schema: Write a brief schema documentation file describing each table’s purpose and its main fields.

**Comment by Forsm0** [comment]
This task is now ready to be picked up. If you have any concerns about the set deadline, please let me know. If you get stuck, please don't hesitate to reach out. We are all in this together. Lets goo

**Comment by ShajiRahman** [comment]
Can some share the updated class diagram please ?

**Comment by ShajiRahman** [comment]
What are the 5 tables that we have decided ?

**Comment by Forsm0** [comment]
any updates on this?

**Comment by ammadkhan34** [comment]
yes @ShajiRahman  got the 6 tables and i think is designing

**Comment by ammadkhan34** [comment]
@Forsm0  when would you be available for a team discussion

**Comment by ShajiRahman** [comment]
Yes I completed designing the database for our project, we can have a review and discuss it in the next group meeting.

**Comment by Forsm0** [comment]
can you please share what you have

**Comment by ShajiRahman** [comment]
[Logical Design Of Database.pdf](https://github.com/user-attachments/files/17967514/Logical.Design.Of.Database.pdf)
