### ISSUE TITLE
Sprint 3: Advanced Front-End Interactivity

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#26]
Priority: Medium
Description: Add interactivity to PUG templates for a fully functional user experience.

- [ ] Implement Interactive Elements: Add interactivity to templates, such as dynamic form submission for reservations or menu selections.

- [ ] Enhance UI Styling: Refine styling and layout in PUG templates for a consistent and user-friendly experience.

- [ ] Final Review of PUG Templates: Ensure all templates reflect the intended design and functionality as outlined in wireframes.

**Comment by ammadkhan34** [comment]
who wants to start work on this?

**Comment by Forsm0** [comment]
Im working on this

**Comment by Ammad12344321** [comment]
Yeah sure can you update which screen you are working on and what's the progress on that yet

**Comment by Forsm0** [comment]
Ive started to look over the layout and the code in general, as suggested by Momina
