### ISSUE TITLE
Sprint 2: Create Activity Diagrams

### ISSUE THREAD

**Issue by eniola07** [Forsm0/SWD-DineSmart#4]

**Comment by Forsm0** [comment]
Notes:
1) The "PRE CANCELLATION" box is placed after "Make Reservations / Pre Order," but the flow doesn’t show what happens after the cancellation. Does it return to the main menu, or is there an additional step, like notifying the restaurant or updating the availability? This part might need more clarity.

2) It would be helpful to add more "End" points where appropriate. For instance, after viewing restaurants or updating availability, the process might stop for that actor. This can help distinguish the end of the flow for both the customer and the restaurant owner.

3) The diagram uses "Customer Account" and "Owner Account," but earlier parts of oue user stories mention "Restaurant Owner."  consistent naming across diagrams and user stories for clarity.

4) You could enhance it by adding more interaction details. For example, after a customer views available tables and menus, is there an option to return to browsing? Including these kinds of decision nodes may help.

**Comment by Forsm0** [comment]
Should include swim lanes

**Comment by eniola07** [comment]
OK .

**Comment by ammadkhan34** [comment]
@Forsm0  Are we adding any updates for review given by momina
