### ISSUE TITLE
Sprint 2: Create User Flow Diagrams

### ISSUE THREAD

**Issue by ammadkhan34** [Forsm0/SWD-DineSmart#5]

**Comment by ammadkhan34** [comment]
got some updates to add after review

**Comment by ShajiRahman** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)

**Comment by ammadkhan34** [comment]
added logout flow and user profile section
