### ISSUE TITLE
Sprint 2: Create Use Case Diagrams

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#6]

**Comment by Forsm0** [comment]
Suggestions:
Add the payment feature and automated email use cases.
Consider linking pre-order meals to the menu for better clarity.
Label your actors more specifically (e.g., "Customer," "Restaurant Admin").
Merge Register and Account Creation if they represent the same process.

**Comment by ammadkhan34** [comment]
@ShajiRahman  can you add a link of document in here

**Comment by ammadkhan34** [comment]
@ShajiRahman  can you share draw.io file also here

**Comment by ammadkhan34** [comment]
@Forsm0  Are we adding any updates for review given by momina
