### ISSUE TITLE
Sprint 2: Design Rough Screen Wireframes

### ISSUE THREAD

**Issue by Forsm0** [Forsm0/SWD-DineSmart#7]

**Comment by ShajiRahman** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)

**Comment by ammadkhan34** [comment]
its in progress

**Comment by ammadkhan34** [comment]
added logout flow and user profile section in figma
