### ISSUE TITLE
Sprint 2: Create State Diagrams

### ISSUE THREAD

**Issue by eniola07** [Forsm0/SWD-DineSmart#8]

**Comment by ShajiRahman** [comment]
[Link to Google docs](https://docs.google.com/document/d/1knK9qGBHRlzWXjasqX0RkYCM5fsVh7f9iWgEb-ocHmk/edit?usp=sharing)

**Comment by eniola07** [comment]
okay

**Comment by Forsm0** [comment]
Try updating your state diagram so it shows the different states your system can be in and how it switches between them. This way, it won’t just look like a list of steps but will show how the system behaves and changes over time.

**Comment by eniola07** [comment]
As discussed on WhatsApp ,this has been handled as we would be going with the changes you suggested ,moving this ticket to done
